version: '3'
services:
  
  mongodb:
    build:
      context: mongo
    image: '${REPO}/rs-mongodb:${TAG}'
    container_name: mongodb
    networks:
      - app_network

  redis:
    image: 'redis:4.0.6'
    container_name: redis
    networks:
      - app_network

  rabbitmq:
    image: 'rabbitmq:3.7-management-alpine'
    container_name: rabbitmq
    networks:
      - app_network

  catalogue:
    build:
      context: catalogue
    image: '${REPO}/rs-catalogue:${TAG}'
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - app_network

  user:
    build:
      context: user
    image: '${REPO}/rs-user:${TAG}'
    container_name: user
    depends_on:
      - mongodb
      - redis
    networks:
      - app_network

  cart:
    build:
      context: cart
    image: '${REPO}/rs-cart:${TAG}'
    container_name: cart
    depends_on:
      - redis
    networks:
      - app_network

  mysql:
    build:
      context: mysql
    image: '${REPO}/rs-mysql-db:${TAG}'
    container_name: mysql
    cap_add:
      - NET_ADMIN
    networks:
      - app_network

  shipping:
    build:
      context: shipping
    image: '${REPO}/rs-shipping:${TAG}'
    container_name: shipping
    depends_on:
      - mysql
    networks:
      - app_network

  ratings:
    build:
      context: ratings
    image: '${REPO}/rs-ratings:${TAG}'
    container_name: ratings
    networks:
      - app_network
    depends_on:
      - mysql

  payment:
    build:
      context: payment
    image: '${REPO}/rs-payment:${TAG}'
    container_name: payment
    depends_on:
      - rabbitmq
    networks:
      - app_network

  dispatch:
    build:
      context: dispatch
    image: '${REPO}/rs-dispatch:${TAG}'
    container_name: dispatch
    depends_on:
      - rabbitmq
    networks:
      - app_network

  web:
    build:
      context: web
    image: '${REPO}/rs-web:${TAG}'
    container_name: web
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - '8080:8080'
    networks:
      - app_network

networks:
  app_network: null
