version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672"
      - "15672:15672"
    networks:
      - app_network

  payment:
    build:
      context: ../payment
    image: steveww/rs-payment
    container_name: payment
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - app_network

  dispatch:
    build:
      context: .
    image: steveww/rs-dispatch
    container_name: dispatch
    depends_on:
      - rabbitmq
    networks:
      - app_network

networks:
  app_network:
